# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven # как называется Workflow

on: [push, pull_request] # когда срабатывает (на push, pull_request)

jobs: # какие задачи делаем
  build: # сборка
    runs-on: ubuntu-latest # на какой ОС запускаем

    steps: # какие шаги выполняем
      - uses: actions/checkout@v2 # выкачиваем репо
      - name: Set up JDK 11
        uses: actions/setup-java@v1 # устанавливаем JDK
        with:
          java-version: 11 # версия для установки
      - name: Build with Maven
        run: mvn -B -e verify # запускаем Maven (фаил в pom в корневой дирректории - указывать не обязательно)
